create entities, repositories, services (User, Role)
Baldinini/bank-service pull request #1
Opened 2021-03-01 15:02 UTC by Baldinini

2021-03-01 16:02 UTC, YuraBondarenko approved these changes

2021-03-01 16:44 UTC, KseniiaMakarova requested changes
please add checkstyle plugin as well

2021-03-01 16:44 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservice/repository/UserRepository.java
> +    Optional<User> findByPhoneNumber(String phoneNumber);
please see checklist - we should fetch roles along with user in this method and in `findById()` as well

2021-03-01 16:44 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservice/service/UserService.java
> +    void create(User user);
```suggestion
    void save(User user);
```

2021-03-01 16:44 UTC, KseniiaMakarova commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
let's enable the console as well so that we could access h2 DB from the browser

2021-03-01 17:22 UTC, KseniiaMakarova requested changes
what about checkstyle plugin?

2021-03-01 17:51 UTC, KseniiaMakarova requested changes

2021-03-01 17:51 UTC, KseniiaMakarova commented on pom.xml
> +                <artifactId>maven-war-plugin</artifactId>
is it the correct plugin?

2021-03-02 07:38 UTC, KseniiaMakarova approved these changes

2021-03-02 08:28 UTC, merged